### ISSUE TITLE
Cannot build app in XCode

### ISSUE THREAD

**Issue by gerson-scanapieco** [greenaddress/WalletCordova#32]
Hello, I`m trying to build the app in Mac OS X Yosemite 10.10.4 with Xcode 6.4, Cordova 5.1.1 and cordova platform ios 3.5.0. I`m getting the following error 2 times:

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_bip38", referenced from:
      objc-class-ref in BIP38Vectors.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by greenaddress** [comment]
Hi, I didn't try with Cordova 5.1.1 (we don't support it yet) but I just tried yesterday on a new mac with latest xcode.

After install npm, I had to install cordova and used the latest 3.x version

npm install cordova@3.6.3-0.2.13

I didn't have any error in building (using cordova build ios)

We'll look into upgrading to the latest cordova but I think it will take a bit, quite a few things seem to have changed (and we need to handle both iOS and Android and maybe even windows phone)

**Comment by gerson-scanapieco** [comment]
Hello,

I'm new to Cordova, seems like it was my fault I could not build it. I managed to build it for iOS in both Cordova 3.6.3 and 5.1.1 and in XCode as well. But now, when I run the app in the iOS simulator for iphone 4S and iOS 8.4 I get the message 'ERROR: Method 'requestAllPaths:' not defined in Plugin 'File''... Do you know what may be causing it?

**Comment by greenaddress** [comment]
This should be fixed now
